// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// NilFields nil fields
// swagger:model NilFields
type NilFields struct {

	// id
	ID string `json:"id,omitempty"`

	// optional
	Optional *string `json:"optional,omitempty"`
}

// Validate validates this nil fields
func (m *NilFields) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *NilFields) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *NilFields) UnmarshalBinary(b []byte) error {
	var res NilFields
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
