package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

// NilFields nil fields
// swagger:model NilFields
type NilFields struct {

	// id
	ID string `json:"id,omitempty"`

	// optional
	Optional *string `json:"optional,omitempty"`
}

// Validate validates this nil fields
func (m *NilFields) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
