// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ThingWithUnderscores thing with underscores
//
// swagger:model ThingWithUnderscores
type ThingWithUnderscores struct {

	// id app
	IDApp string `json:"id_app,omitempty"`
}

// Validate validates this thing with underscores
func (m *ThingWithUnderscores) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this thing with underscores based on context it is used
func (m *ThingWithUnderscores) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ThingWithUnderscores) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ThingWithUnderscores) UnmarshalBinary(b []byte) error {
	var res ThingWithUnderscores
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
