// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ThingWithDateRange thing with date range
// swagger:model ThingWithDateRange
type ThingWithDateRange struct {

	// date
	Date strfmt.DateTime `json:"date,omitempty"`

	// name
	Name string `json:"name,omitempty"`
}

// Validate validates this thing with date range
func (m *ThingWithDateRange) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *ThingWithDateRange) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ThingWithDateRange) UnmarshalBinary(b []byte) error {
	var res ThingWithDateRange
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
