package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

// AuthorsResponseMetadata authors response metadata
// swagger:model AuthorsResponseMetadata
type AuthorsResponseMetadata struct {

	// count
	Count int64 `json:"count,omitempty"`
}

// Validate validates this authors response metadata
func (m *AuthorsResponseMetadata) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
