// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// Dog dog
// swagger:model Dog
type Dog struct {
	Pet

	Identifiable

	// breed
	Breed string `json:"breed,omitempty"`
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *Dog) UnmarshalJSON(raw []byte) error {

	var aO0 Pet
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	m.Pet = aO0

	var aO1 Identifiable
	if err := swag.ReadJSON(raw, &aO1); err != nil {
		return err
	}
	m.Identifiable = aO1

	var data struct {
		Breed string `json:"breed,omitempty"`
	}
	if err := swag.ReadJSON(raw, &data); err != nil {
		return err
	}

	m.Breed = data.Breed

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m Dog) MarshalJSON() ([]byte, error) {
	var _parts [][]byte

	aO0, err := swag.WriteJSON(m.Pet)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)

	aO1, err := swag.WriteJSON(m.Identifiable)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO1)

	var data struct {
		Breed string `json:"breed,omitempty"`
	}

	data.Breed = m.Breed

	jsonData, err := swag.WriteJSON(data)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, jsonData)

	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this dog
func (m *Dog) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.Pet.Validate(formats); err != nil {
		res = append(res, err)
	}

	if err := m.Identifiable.Validate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *Dog) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Dog) UnmarshalBinary(b []byte) error {
	var res Dog
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
