package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

// InternalError internal error
// swagger:model InternalError
type InternalError struct {

	// msg
	Msg string `json:"msg,omitempty"`
}

// Validate validates this internal error
func (m *InternalError) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
