package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

// Unathorized unathorized
// swagger:model Unathorized
type Unathorized struct {

	// msg
	Msg string `json:"msg,omitempty"`
}

// Validate validates this unathorized
func (m *Unathorized) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
