image: clever/drone-go:1.7
notify:
  email:
    recipients:
    - drone@clever.com
  slack:
    on_failure: true
    on_started: false
    on_success: false
    webhook_url: $$slack_webhook
publish:
  report_card: {}
  github:
    artifacts:
    - release
    repo: wag
    script:
    - make release
    tag: v$(cat VERSION)
    token: $$github_token
    user: Clever
    when:
      branch: master
script:
# install dependencies
- make install_deps
- cp .tmp/circuit vendor/github.com/afex/hystrix-go/hystrix/circuit.go
- make test
- make build
