env:
- REPORT_CARD_GITHUB_STATUS_TOKEN=$$report_card_github_status_token
- REPORT_CARD_GITHUB_REPO_TOKEN=$$report_card_github_repo_token
image: clever/drone-go:1.7
notify:
  email:
    recipients:
    - drone@clever.com
  slack:
    on_failure: true
    on_started: false
    on_success: false
    webhook_url: $$slack_webhook
publish:
  docker:
    docker_host: $$docker_server
    email: $$docker_email
    image_name: clever/wag
    password: $$docker_password
    registry_login: true
    tags:
    - $(git rev-parse --short HEAD)
    - latest
    username: $$docker_username
    when:
      branch: master
script:
# setup ssh key, to install private dependencies
- echo ${drone_key} | sed 's|\\n|\n|g' > ~/.ssh/id_rsa
- chmod 600 ~/.ssh/id_rsa
# install dependencies
- make install_deps
- make test
- make build
