required = ["github.com/tmthrgd/go-bindata", "github.com/golang/mock/mockgen", "github.com/go-openapi/jsonpointer"]
[[constraint]]
  name = "github.com/Clever/discovery-go"
  branch = "master"

[[constraint]]
  name = "github.com/Clever/go-process-metrics"
  branch = "master"

[[constraint]]
  name = "github.com/Clever/go-utils"
  branch = "master"

[[constraint]]
  name = "github.com/afex/hystrix-go"
  branch = "master"

[[constraint]]
  name = "github.com/donovanhide/eventsource"
  branch = "master"

[[constraint]]
  name = "github.com/go-errors/errors"
  version = "1.0.0"

[[constraint]]
  name = "github.com/go-openapi/errors"
  version = "0.19.7"

[[constraint]]
  name = "github.com/go-openapi/jsonreference"
  version = "0.19.4"

[[constraint]]
  name = "github.com/go-openapi/loads"
  version = "0.19.5"

[[constraint]]
  name = "github.com/go-openapi/spec"
  version = "0.19.9"

[[constraint]]
  name = "github.com/go-openapi/strfmt"
  version = "0.19.5"

[[constraint]]
  name = "github.com/go-openapi/jsonpointer"
  version = "0.19.3"

[[constraint]]
  name = "github.com/go-openapi/swag"
  version = "0.19.9"

[[constraint]]
  name = "github.com/go-openapi/validate"
  version = "0.19.11"

[[constraint]]
  name = "github.com/go-swagger/go-swagger"
  version = "0.25.0"

[[constraint]]
  name = "github.com/golang/mock"
  branch = "master"

[[constraint]]
  name = "github.com/tmthrgd/go-bindata"
  branch = "master"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.6.1"

[[constraint]]
  name = "github.com/kardianos/osext"
  branch = "master"

[[constraint]]
  name = "github.com/uber/jaeger-client-go"
  version = "2.16.0"

[[constraint]]
  name = "github.com/opentracing/opentracing-go"
  version = "1.1.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.1"

[[constraint]]
  name = "golang.org/x/net"
  branch = "master"

[[constraint]]
  name = "gopkg.in/Clever/kayvee-go.v6"
  version = "^6.17.0"

[[constraint]]
  name = "gopkg.in/mgo.v2"
  branch = "v2"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  branch = "v2"

[[constraint]]
  branch = "master"
  name = "github.com/awslabs/goformation"

[[constraint]]
  branch = "master"
  name = "golang.org/x/time"

[[constraint]]
  branch = "master"
  name = "github.com/opentracing-contrib/go-aws-sdk"

[[constraint]]
  branch = "master"
  name = "golang.org/x/xerrors"

[[constraint]]
  name = "github.com/gorilla/handlers"
  version = "1.4.2"
