required = ["github.com/tmthrgd/go-bindata", "github.com/golang/mock/mockgen"]
[[constraint]]
  name = "github.com/Clever/discovery-go"
  branch = "master"

[[constraint]]
  name = "github.com/Clever/go-process-metrics"
  branch = "master"

[[constraint]]
  name = "github.com/Clever/go-utils"
  branch = "master"

[[constraint]]
  name = "github.com/afex/hystrix-go"
  branch = "master"

[[constraint]]
  name = "github.com/donovanhide/eventsource"
  branch = "master"

[[constraint]]
  name = "github.com/go-errors/errors"
  version = "1.0.0"

[[constraint]]
  name = "github.com/go-openapi/errors"
  branch = "master"

[[constraint]]
  name = "github.com/go-openapi/jsonreference"
  branch = "master"

[[constraint]]
  name = "github.com/go-openapi/loads"
  branch = "master"

[[constraint]]
  name = "github.com/go-openapi/spec"
  branch = "master"

[[constraint]]
  name = "github.com/go-openapi/strfmt"
  branch = "master"

[[constraint]]
  name = "github.com/go-openapi/swag"
  branch = "master"

[[constraint]]
  name = "github.com/go-openapi/validate"
  branch = "master"

[[constraint]]
  name = "github.com/go-swagger/go-swagger"
  version = "0.13.0"

[[constraint]]
  name = "github.com/golang/mock"
  branch = "master"

[[constraint]]
  name = "github.com/tmthrgd/go-bindata"
  branch = "master"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.6.1"

[[constraint]]
  name = "github.com/kardianos/osext"
  branch = "master"

[[constraint]]
  name = "github.com/uber/jaeger-client-go"
  branch = "master"

[[constraint]]
  name = "github.com/opentracing/opentracing-go"
  version = "1.0.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.1"

[[constraint]]
  name = "golang.org/x/net"
  branch = "master"

[[constraint]]
  name = "gopkg.in/Clever/kayvee-go.v6"
  version = "6.0.0"

[[constraint]]
  name = "gopkg.in/mgo.v2"
  branch = "v2"

[[constraint]]
  name = "gopkg.in/tylerb/graceful.v1"
  version = "1.0.0"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  branch = "v2"

[[constraint]]
  branch = "master"
  name = "github.com/awslabs/goformation"

[[constraint]]
  branch = "master"
  name = "golang.org/x/time"

[[constraint]]
  branch = "master"
  name = "github.com/icza/dyno"
