swagger: '2.0'
info:
  title: swagger-test
  description: Testing Swagger Codegen
  version: 0.1.0
basePath: /v1
schemes:
  - http
produces:
  - application/json
consumes:
  - application/json

paths:
  /books/{id}:
    delete:
      operationId: deleteBook
      parameters:
        - name: id
          in: path
          required: true
          type: string
      responses:
        200:
          description: OK response
        404:
          description: OK response