swagger: '2.0'
info:
  title: Swagger Test
  description: Testing Swagger Codegen
  version: 0.1.0
basePath: /v1
schemes:
  - http
produces:
  - application/json
consumes:
  - application/json
paths:
  /books/{bookID}:
    get:
      operationId: getBookByID
      description: Returns a book
      parameters:
        - name: bookID
          in: path
          type: integer
          required: true
          maximum: 10000000
          minimum: 2
          # This is a silly requirement, but let's add it to show how it would work
          multipleOf: 2
        - name: authorization
          in: header
          type: string
          minLength: 1
          maxLength: 24
          pattern: "[0-9a-f]+"
        - name: randomBytes
          in: query
          type: string
          format: byte
      responses:
        200:
          description: "Success"
          schema:
            $ref: "#/definitions/Book"
        204:
          description: "No content"
        401:
          description: "Unauthorized"
        404:
          description: "Not found"
          schema:
            $ref: "#/definitions/Error"
        default:
          description: "Error"
          schema:
            $ref: "#/definitions/Error"
    post:
      operationId: createBook
      description: Creates a book
      parameters:
        - name: newBook
          in: body
          schema:
            $ref: "#/definitions/Book"
      responses:
        200:
          description: "Success"
          schema:
            $ref: "#/definitions/Book"
        default:
          description: "Error"
          schema:
            $ref: "#/definitions/Error"
  /books:
    get:
      operationId: getBooks
      description: Returns a list of books
      parameters:
        - name: author
          in: query
          type: string
        - name: available
          in: query
          type: boolean
          default: true
        - name: state
          in: query
          type: string
          required: false
          enum:
            - finished
            - inprogress
          default: finished
        - name: published
          in: query
          type: string
          format: date
        - name: completed
          in: query
          type: string
          format: date-time
        - name: maxPages
          in: query
          # Probably makes more sense for this to be an integer, but I couldn't figure out
          # a good example for books that really would need a float
          type: number
          maximum: 1000
          minimum: -5
          multipleOf: 0.5
          default: 500.5
        - name: minPages
          in: query
          type: integer
          format: int32
          default: 5
        - name: pagesToTime
          in: query
          type: number
          format: float
      responses:
        200:
          description: "Success"
          schema:
            type: array
            items:
              $ref: "#/definitions/Book"
        default:
          description: "Error"
          schema:
            $ref: "#/definitions/Error"
definitions:
  Book:
    type: object
    properties:
      id:
        type: integer
      name:
        type: string
  Error:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
