// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ThingWithDateTimeComposite thing with date time composite
//
// swagger:model ThingWithDateTimeComposite
type ThingWithDateTimeComposite struct {

	// created
	// Format: date-time
	Created strfmt.DateTime `json:"created,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// resource
	Resource string `json:"resource,omitempty"`

	// type
	Type string `json:"type,omitempty"`
}

// Validate validates this thing with date time composite
func (m *ThingWithDateTimeComposite) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCreated(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ThingWithDateTimeComposite) validateCreated(formats strfmt.Registry) error {
	if swag.IsZero(m.Created) { // not required
		return nil
	}

	if err := validate.FormatOf("created", "body", "date-time", m.Created.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this thing with date time composite based on context it is used
func (m *ThingWithDateTimeComposite) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ThingWithDateTimeComposite) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ThingWithDateTimeComposite) UnmarshalBinary(b []byte) error {
	var res ThingWithDateTimeComposite
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
