// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ThingWithMatchingKeys thing with matching keys
// swagger:model ThingWithMatchingKeys
type ThingWithMatchingKeys struct {

	// assoc ID
	AssocID string `json:"assocID,omitempty"`

	// assoc type
	AssocType string `json:"assocType,omitempty"`

	// bear
	Bear string `json:"bear,omitempty"`

	// created
	Created strfmt.DateTime `json:"created,omitempty"`
}

// Validate validates this thing with matching keys
func (m *ThingWithMatchingKeys) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *ThingWithMatchingKeys) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ThingWithMatchingKeys) UnmarshalBinary(b []byte) error {
	var res ThingWithMatchingKeys
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
