// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// AppSchema app schema
// swagger:model AppSchema
type AppSchema struct {

	// collection schemas
	CollectionSchemas []*CollectionSchema `json:"collectionSchemas"`

	// needs propagation
	NeedsPropagation bool `json:"needsPropagation,omitempty"`
}

// Validate validates this app schema
func (m *AppSchema) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCollectionSchemas(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AppSchema) validateCollectionSchemas(formats strfmt.Registry) error {

	if swag.IsZero(m.CollectionSchemas) { // not required
		return nil
	}

	for i := 0; i < len(m.CollectionSchemas); i++ {

		if swag.IsZero(m.CollectionSchemas[i]) { // not required
			continue
		}

		if m.CollectionSchemas[i] != nil {

			if err := m.CollectionSchemas[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("collectionSchemas" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *AppSchema) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AppSchema) UnmarshalBinary(b []byte) error {
	var res AppSchema
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
