// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// CreateLibraryResourceRequest create library resource request
// swagger:model CreateLibraryResourceRequest
type CreateLibraryResourceRequest struct {

	// clever ID
	// Min Length: 1
	CleverID *string `json:"cleverID,omitempty"`
}

// Validate validates this create library resource request
func (m *CreateLibraryResourceRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCleverID(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CreateLibraryResourceRequest) validateCleverID(formats strfmt.Registry) error {

	if swag.IsZero(m.CleverID) { // not required
		return nil
	}

	if err := validate.MinLength("cleverID", "body", string(*m.CleverID), 1); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *CreateLibraryResourceRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CreateLibraryResourceRequest) UnmarshalBinary(b []byte) error {
	var res CreateLibraryResourceRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
