// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
)

// GuideData guide data
// swagger:model GuideData
type GuideData map[string]interface{}

// Validate validates this guide data
func (m GuideData) Validate(formats strfmt.Registry) error {
	return nil
}
