// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// InsightsMetadata insights metadata
// swagger:model InsightsMetadata
type InsightsMetadata struct {

	// enabled
	Enabled bool `json:"enabled,omitempty"`

	// usage urls
	UsageUrls []string `json:"usageUrls"`
}

// Validate validates this insights metadata
func (m *InsightsMetadata) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateUsageUrls(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *InsightsMetadata) validateUsageUrls(formats strfmt.Registry) error {

	if swag.IsZero(m.UsageUrls) { // not required
		return nil
	}

	return nil
}

// MarshalBinary interface implementation
func (m *InsightsMetadata) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *InsightsMetadata) UnmarshalBinary(b []byte) error {
	var res InsightsMetadata
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
