// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// LibraryResource A resource to show in the Clever Library
// swagger:model LibraryResource
type LibraryResource struct {

	// app onboarding
	AppOnboarding *AppOnboarding `json:"appOnboarding,omitempty"`

	// banner icon URL
	BannerIconURL string `json:"bannerIconURL,omitempty"`

	// categories
	Categories *ResourceCategories `json:"categories,omitempty"`

	// certifications
	Certifications *ResourceCertifications `json:"certifications,omitempty"`

	// clever ID
	CleverID string `json:"cleverID,omitempty"`

	// covid promotion
	CovidPromotion string `json:"covidPromotion,omitempty"`

	// description
	Description string `json:"description,omitempty"`

	// devices
	Devices *ResourceDevices `json:"devices,omitempty"`

	// featured
	Featured int32 `json:"featured,omitempty"`

	// features
	Features ResourceFeatures `json:"features"`

	// grade levels
	GradeLevels *ResourceGradeLevels `json:"gradeLevels,omitempty"`

	// icon URL
	IconURL string `json:"iconURL,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// insights
	Insights *InsightsMetadata `json:"insights,omitempty"`

	// install count
	InstallCount int32 `json:"installCount,omitempty"`

	// library integration
	LibraryIntegration LibraryIntegrationType `json:"libraryIntegration,omitempty"`

	// marketing collateral status
	MarketingCollateralStatus MarketingCollateralStatus `json:"marketingCollateralStatus,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// pricing
	Pricing ResourcePricing `json:"pricing,omitempty"`

	// privacy policy URL
	PrivacyPolicyURL string `json:"privacyPolicyURL,omitempty"`

	// search tags
	SearchTags []string `json:"searchTags"`

	// shortname
	Shortname string `json:"shortname,omitempty"`

	// show in library
	ShowInLibrary bool `json:"showInLibrary,omitempty"`

	// stripe user ID
	StripeUserID string `json:"stripeUserID,omitempty"`

	// tagline
	Tagline string `json:"tagline,omitempty"`

	// teacher setup guide
	TeacherSetupGuide *TeacherSetupGuide `json:"teacherSetupGuide,omitempty"`

	// teacher setup guide status
	TeacherSetupGuideStatus TeacherSetupGuideStatus `json:"teacherSetupGuideStatus,omitempty"`

	// tiers
	Tiers Tiers `json:"tiers"`

	// tos URL
	TosURL string `json:"tosURL,omitempty"`

	// universal d s a signatory
	UniversalDSASignatory bool `json:"universalDSASignatory,omitempty"`

	// url
	URL string `json:"url,omitempty"`
}

// Validate validates this library resource
func (m *LibraryResource) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAppOnboarding(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateCategories(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateCertifications(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateDevices(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateGradeLevels(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateInsights(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateLibraryIntegration(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateMarketingCollateralStatus(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validatePricing(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateSearchTags(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateTeacherSetupGuide(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateTeacherSetupGuideStatus(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *LibraryResource) validateAppOnboarding(formats strfmt.Registry) error {

	if swag.IsZero(m.AppOnboarding) { // not required
		return nil
	}

	if m.AppOnboarding != nil {

		if err := m.AppOnboarding.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("appOnboarding")
			}
			return err
		}
	}

	return nil
}

func (m *LibraryResource) validateCategories(formats strfmt.Registry) error {

	if swag.IsZero(m.Categories) { // not required
		return nil
	}

	if m.Categories != nil {

		if err := m.Categories.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("categories")
			}
			return err
		}
	}

	return nil
}

func (m *LibraryResource) validateCertifications(formats strfmt.Registry) error {

	if swag.IsZero(m.Certifications) { // not required
		return nil
	}

	if m.Certifications != nil {

		if err := m.Certifications.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("certifications")
			}
			return err
		}
	}

	return nil
}

func (m *LibraryResource) validateDevices(formats strfmt.Registry) error {

	if swag.IsZero(m.Devices) { // not required
		return nil
	}

	if m.Devices != nil {

		if err := m.Devices.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("devices")
			}
			return err
		}
	}

	return nil
}

func (m *LibraryResource) validateGradeLevels(formats strfmt.Registry) error {

	if swag.IsZero(m.GradeLevels) { // not required
		return nil
	}

	if m.GradeLevels != nil {

		if err := m.GradeLevels.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("gradeLevels")
			}
			return err
		}
	}

	return nil
}

func (m *LibraryResource) validateInsights(formats strfmt.Registry) error {

	if swag.IsZero(m.Insights) { // not required
		return nil
	}

	if m.Insights != nil {

		if err := m.Insights.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("insights")
			}
			return err
		}
	}

	return nil
}

func (m *LibraryResource) validateLibraryIntegration(formats strfmt.Registry) error {

	if swag.IsZero(m.LibraryIntegration) { // not required
		return nil
	}

	if err := m.LibraryIntegration.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("libraryIntegration")
		}
		return err
	}

	return nil
}

func (m *LibraryResource) validateMarketingCollateralStatus(formats strfmt.Registry) error {

	if swag.IsZero(m.MarketingCollateralStatus) { // not required
		return nil
	}

	if err := m.MarketingCollateralStatus.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("marketingCollateralStatus")
		}
		return err
	}

	return nil
}

func (m *LibraryResource) validatePricing(formats strfmt.Registry) error {

	if swag.IsZero(m.Pricing) { // not required
		return nil
	}

	if err := m.Pricing.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("pricing")
		}
		return err
	}

	return nil
}

func (m *LibraryResource) validateSearchTags(formats strfmt.Registry) error {

	if swag.IsZero(m.SearchTags) { // not required
		return nil
	}

	return nil
}

func (m *LibraryResource) validateTeacherSetupGuide(formats strfmt.Registry) error {

	if swag.IsZero(m.TeacherSetupGuide) { // not required
		return nil
	}

	if m.TeacherSetupGuide != nil {

		if err := m.TeacherSetupGuide.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("teacherSetupGuide")
			}
			return err
		}
	}

	return nil
}

func (m *LibraryResource) validateTeacherSetupGuideStatus(formats strfmt.Registry) error {

	if swag.IsZero(m.TeacherSetupGuideStatus) { // not required
		return nil
	}

	if err := m.TeacherSetupGuideStatus.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("teacherSetupGuideStatus")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *LibraryResource) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *LibraryResource) UnmarshalBinary(b []byte) error {
	var res LibraryResource
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
