// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PatchAdminRequest patch admin request
// swagger:model PatchAdminRequest
type PatchAdminRequest struct {

	// email
	// Min Length: 1
	Email *string `json:"email,omitempty"`

	// name
	// Min Length: 1
	Name *string `json:"name,omitempty"`

	// password
	Password *string `json:"password,omitempty"`

	// phone
	Phone *string `json:"phone,omitempty"`

	// two factor
	TwoFactor *TwoFactor `json:"twoFactor,omitempty"`
}

// Validate validates this patch admin request
func (m *PatchAdminRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateEmail(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateName(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateTwoFactor(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PatchAdminRequest) validateEmail(formats strfmt.Registry) error {

	if swag.IsZero(m.Email) { // not required
		return nil
	}

	if err := validate.MinLength("email", "body", string(*m.Email), 1); err != nil {
		return err
	}

	return nil
}

func (m *PatchAdminRequest) validateName(formats strfmt.Registry) error {

	if swag.IsZero(m.Name) { // not required
		return nil
	}

	if err := validate.MinLength("name", "body", string(*m.Name), 1); err != nil {
		return err
	}

	return nil
}

func (m *PatchAdminRequest) validateTwoFactor(formats strfmt.Registry) error {

	if swag.IsZero(m.TwoFactor) { // not required
		return nil
	}

	if m.TwoFactor != nil {

		if err := m.TwoFactor.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("twoFactor")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *PatchAdminRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PatchAdminRequest) UnmarshalBinary(b []byte) error {
	var res PatchAdminRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
