// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// PatchPlatformRequest Used for an update to a platform
// swagger:model PatchPlatformRequest
type PatchPlatformRequest struct {

	// disabled
	Disabled bool `json:"disabled,omitempty"`

	// redirect uris
	RedirectUris []*RedirectURI `json:"redirectUris"`
}

// Validate validates this patch platform request
func (m *PatchPlatformRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateRedirectUris(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PatchPlatformRequest) validateRedirectUris(formats strfmt.Registry) error {

	if swag.IsZero(m.RedirectUris) { // not required
		return nil
	}

	for i := 0; i < len(m.RedirectUris); i++ {

		if swag.IsZero(m.RedirectUris[i]) { // not required
			continue
		}

		if m.RedirectUris[i] != nil {

			if err := m.RedirectUris[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("redirectUris" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *PatchPlatformRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PatchPlatformRequest) UnmarshalBinary(b []byte) error {
	var res PatchPlatformRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
