// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// RelatedAppsV2 related apps v2
// swagger:model RelatedAppsV2
type RelatedAppsV2 struct {

	// analytics
	Analytics *string `json:"analytics,omitempty"`

	// district partners
	DistrictPartners []string `json:"districtPartners"`

	// library
	Library []string `json:"library"`

	// saml
	Saml []string `json:"saml"`

	// saved passwords
	SavedPasswords []string `json:"savedPasswords"`
}

// Validate validates this related apps v2
func (m *RelatedAppsV2) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDistrictPartners(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateLibrary(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateSaml(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateSavedPasswords(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *RelatedAppsV2) validateDistrictPartners(formats strfmt.Registry) error {

	if swag.IsZero(m.DistrictPartners) { // not required
		return nil
	}

	return nil
}

func (m *RelatedAppsV2) validateLibrary(formats strfmt.Registry) error {

	if swag.IsZero(m.Library) { // not required
		return nil
	}

	return nil
}

func (m *RelatedAppsV2) validateSaml(formats strfmt.Registry) error {

	if swag.IsZero(m.Saml) { // not required
		return nil
	}

	return nil
}

func (m *RelatedAppsV2) validateSavedPasswords(formats strfmt.Registry) error {

	if swag.IsZero(m.SavedPasswords) { // not required
		return nil
	}

	return nil
}

// MarshalBinary interface implementation
func (m *RelatedAppsV2) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RelatedAppsV2) UnmarshalBinary(b []byte) error {
	var res RelatedAppsV2
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
