// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ResourceDevices resource devices
// swagger:model ResourceDevices
type ResourceDevices struct {

	// android
	Android bool `json:"android,omitempty"`

	// browser
	Browser bool `json:"browser,omitempty"`

	// i o s
	IOS bool `json:"iOS,omitempty"`

	// mac o s
	MacOS bool `json:"macOS,omitempty"`

	// windows
	Windows bool `json:"windows,omitempty"`
}

// Validate validates this resource devices
func (m *ResourceDevices) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *ResourceDevices) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ResourceDevices) UnmarshalBinary(b []byte) error {
	var res ResourceDevices
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
