// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ResourceCategories resource categories
// swagger:model ResourceCategories
type ResourceCategories struct {

	// assessment
	Assessment bool `json:"assessment,omitempty"`

	// authoring
	Authoring bool `json:"authoring,omitempty"`

	// classroom management
	ClassroomManagement bool `json:"classroom_management,omitempty"`

	// english
	English bool `json:"english,omitempty"`

	// math
	Math bool `json:"math,omitempty"`

	// other
	Other bool `json:"other,omitempty"`

	// presentation
	Presentation bool `json:"presentation,omitempty"`

	// science
	Science bool `json:"science,omitempty"`

	// social studies
	SocialStudies bool `json:"social_studies,omitempty"`

	// technology
	Technology bool `json:"technology,omitempty"`
}

// Validate validates this resource categories
func (m *ResourceCategories) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *ResourceCategories) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ResourceCategories) UnmarshalBinary(b []byte) error {
	var res ResourceCategories
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
