// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ResourceCertifications resource certifications
// swagger:model ResourceCertifications
type ResourceCertifications struct {

	// commonsensemedia reviewed
	CommonsensemediaReviewed bool `json:"commonsensemedia_reviewed,omitempty"`

	// ikeepsafe coppa
	IkeepsafeCoppa bool `json:"ikeepsafe_coppa,omitempty"`

	// ikeepsafe ferpa
	IkeepsafeFerpa bool `json:"ikeepsafe_ferpa,omitempty"`

	// student privacy pledge
	StudentPrivacyPledge bool `json:"student_privacy_pledge,omitempty"`
}

// Validate validates this resource certifications
func (m *ResourceCertifications) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *ResourceCertifications) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ResourceCertifications) UnmarshalBinary(b []byte) error {
	var res ResourceCertifications
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
