// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// SecretConfig secret config
// swagger:model SecretConfig
type SecretConfig struct {

	// business token
	BusinessToken string `json:"businessToken,omitempty"`

	// current secret
	CurrentSecret string `json:"currentSecret,omitempty"`

	// old secret
	OldSecret string `json:"oldSecret,omitempty"`

	// old secret expires
	OldSecretExpires strfmt.DateTime `json:"oldSecretExpires,omitempty"`
}

// Validate validates this secret config
func (m *SecretConfig) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *SecretConfig) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SecretConfig) UnmarshalBinary(b []byte) error {
	var res SecretConfig
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
