// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// SetCertificationsRequest Integration certifications for an app, for a specific school year.
// swagger:model SetCertificationsRequest
type SetCertificationsRequest struct {

	// DEPRECATED - use certS3PathIntegration and certS3PathTradeshow instead. This field is mapped to certS3PathTradeshow.
	CertS3Path string `json:"certS3Path,omitempty"`

	// cert s3 path integration
	CertS3PathIntegration string `json:"certS3PathIntegration,omitempty"`

	// cert s3 path tradeshow
	CertS3PathTradeshow string `json:"certS3PathTradeshow,omitempty"`

	// events
	Events bool `json:"events,omitempty"`

	// generic
	Generic bool `json:"generic,omitempty"`

	// goals
	Goals bool `json:"goals,omitempty"`

	// instant login
	InstantLogin bool `json:"instantLogin,omitempty"`

	// DEPRECATED - use nativeMobile instead. This field is mapped to nativeMobile for now.
	Ios bool `json:"ios,omitempty"`

	// native mobile
	NativeMobile bool `json:"nativeMobile,omitempty"`

	// secure sync
	SecureSync bool `json:"secureSync,omitempty"`
}

// Validate validates this set certifications request
func (m *SetCertificationsRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *SetCertificationsRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SetCertificationsRequest) UnmarshalBinary(b []byte) error {
	var res SetCertificationsRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
