// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// SetupStep setup step
// swagger:model SetupStep
type SetupStep struct {

	// app id
	AppID string `json:"app_id,omitempty"`

	// content
	Content string `json:"content,omitempty"`

	// creator
	Creator *string `json:"creator,omitempty"`

	// edit date
	EditDate *string `json:"edit_date,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// title
	Title string `json:"title,omitempty"`
}

// Validate validates this setup step
func (m *SetupStep) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *SetupStep) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SetupStep) UnmarshalBinary(b []byte) error {
	var res SetupStep
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
