// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

// TeacherSetupGuideStatus teacher setup guide status
// swagger:model TeacherSetupGuideStatus
type TeacherSetupGuideStatus string

const (
	// TeacherSetupGuideStatusNotStarted captures enum value "notStarted"
	TeacherSetupGuideStatusNotStarted TeacherSetupGuideStatus = "notStarted"
	// TeacherSetupGuideStatusStarted captures enum value "started"
	TeacherSetupGuideStatusStarted TeacherSetupGuideStatus = "started"
	// TeacherSetupGuideStatusCompleted captures enum value "completed"
	TeacherSetupGuideStatusCompleted TeacherSetupGuideStatus = "completed"
)

// for schema
var teacherSetupGuideStatusEnum []interface{}

func init() {
	var res []TeacherSetupGuideStatus
	if err := json.Unmarshal([]byte(`["notStarted","started","completed"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		teacherSetupGuideStatusEnum = append(teacherSetupGuideStatusEnum, v)
	}
}

func (m TeacherSetupGuideStatus) validateTeacherSetupGuideStatusEnum(path, location string, value TeacherSetupGuideStatus) error {
	if err := validate.Enum(path, location, value, teacherSetupGuideStatusEnum); err != nil {
		return err
	}
	return nil
}

// Validate validates this teacher setup guide status
func (m TeacherSetupGuideStatus) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateTeacherSetupGuideStatusEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
