// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

// TrackableApps trackable apps
// swagger:model TrackableApps
type TrackableApps map[string]TrackableApp

// Validate validates this trackable apps
func (m TrackableApps) Validate(formats strfmt.Registry) error {
	var res []error

	if err := validate.Required("", "body", TrackableApps(m)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
