// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// TrackingWhitelist tracking whitelist
// swagger:model TrackingWhitelist
type TrackingWhitelist struct {

	// enable tracking
	EnableTracking bool `json:"enableTracking,omitempty"`

	// hide in UI
	HideInUI bool `json:"hideInUI,omitempty"`

	// url matchers
	URLMatchers []string `json:"urlMatchers"`
}

// Validate validates this tracking whitelist
func (m *TrackingWhitelist) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateURLMatchers(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TrackingWhitelist) validateURLMatchers(formats strfmt.Registry) error {

	if swag.IsZero(m.URLMatchers) { // not required
		return nil
	}

	return nil
}

// MarshalBinary interface implementation
func (m *TrackingWhitelist) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TrackingWhitelist) UnmarshalBinary(b []byte) error {
	var res TrackingWhitelist
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
