// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// UpdateOnboardingRequest An update to an app's onboarding progress
// swagger:model UpdateOnboardingRequest
type UpdateOnboardingRequest struct {

	// event type
	EventType OnboardingEventType `json:"eventType,omitempty"`

	// integration type
	IntegrationType OnboardingIntegrationType `json:"integrationType,omitempty"`

	// survey
	Survey []*OnboardingSurveyItem `json:"survey"`
}

// Validate validates this update onboarding request
func (m *UpdateOnboardingRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateEventType(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateIntegrationType(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateSurvey(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *UpdateOnboardingRequest) validateEventType(formats strfmt.Registry) error {

	if swag.IsZero(m.EventType) { // not required
		return nil
	}

	if err := m.EventType.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("eventType")
		}
		return err
	}

	return nil
}

func (m *UpdateOnboardingRequest) validateIntegrationType(formats strfmt.Registry) error {

	if swag.IsZero(m.IntegrationType) { // not required
		return nil
	}

	if err := m.IntegrationType.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("integrationType")
		}
		return err
	}

	return nil
}

func (m *UpdateOnboardingRequest) validateSurvey(formats strfmt.Registry) error {

	if swag.IsZero(m.Survey) { // not required
		return nil
	}

	for i := 0; i < len(m.Survey); i++ {

		if swag.IsZero(m.Survey[i]) { // not required
			continue
		}

		if m.Survey[i] != nil {

			if err := m.Survey[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("survey" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *UpdateOnboardingRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UpdateOnboardingRequest) UnmarshalBinary(b []byte) error {
	var res UpdateOnboardingRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
