// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
)

// VerificationCodeResponse verification code response
// swagger:model VerificationCodeResponse
type VerificationCodeResponse string

// Validate validates this verification code response
func (m VerificationCodeResponse) Validate(formats strfmt.Registry) error {
	return nil
}
