// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// VersionSettings Version settings for an application
// swagger:model VersionSettings
type VersionSettings struct {

	// allowed
	Allowed []Version `json:"allowed"`

	// default
	Default Version `json:"default,omitempty"`
}

// Validate validates this version settings
func (m *VersionSettings) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAllowed(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateDefault(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *VersionSettings) validateAllowed(formats strfmt.Registry) error {

	if swag.IsZero(m.Allowed) { // not required
		return nil
	}

	for i := 0; i < len(m.Allowed); i++ {

		if err := m.Allowed[i].Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("allowed" + "." + strconv.Itoa(i))
			}
			return err
		}

	}

	return nil
}

func (m *VersionSettings) validateDefault(formats strfmt.Registry) error {

	if swag.IsZero(m.Default) { // not required
		return nil
	}

	if err := m.Default.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("default")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *VersionSettings) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *VersionSettings) UnmarshalBinary(b []byte) error {
	var res VersionSettings
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
