swagger: '2.0'
info:
  title: swagger-test
  description: Testing Swagger Codegen
  version: 0.1.0
  x-npm-package: swagger-test
basePath: /v1
schemes:
  - http
produces:
  - application/json
consumes:
  - application/json

paths:
  /books/{id}:
    get:
      operationId: getBook
      parameters:
        - name: id
          in: path
          required: true
          type: integer
      deprecated: true
      responses:
        200:
          description: OK response
        404:
          description: OK response
