swagger: '2.0'
info:
  title: swagger-test
  description: Testing Swagger Codegen
  version: 9.0.0
  x-npm-package: swagger-test
basePath: /v1
schemes:
  - http
produces:
  - application/json
consumes:
  - application/json
responses:
  BadRequest:
    description: "Bad Request"
    schema:
      $ref: "#/definitions/BadRequest"
  InternalError:
    description: "Internal Error"
    schema:
      $ref: "#/definitions/InternalError"
paths:
  /health:
    get:
      operationId: health
      parameters:
        - name: section
          in: query
          required: true
          type: integer
      deprecated: true
      responses:
        200:
          description: OK response
        404:
          description: OK response
          schema:
            $ref: "#/definitions/NotFound"

definitions:
  BadRequest:
    type: object
    properties:
      message:
        type: string

  InternalError:
    type: object
    properties:
      message:
        type: string

  NotFound:
    type: object
    properties:
      message:
        type: string
