swagger: '2.0'
info:
  title: swagger-test
  description: Testing Swagger Codegen
  version: 0.1.0
  x-npm-package: swagger-test
basePath: /v1
schemes:
  - http
produces:
  - application/json
consumes:
  - application/json
responses:
  BadRequest:
    description: "Bad Request"
    schema:
      $ref: "#/definitions/ExtendedError"
  InternalError:
    description: "Internal Error"
    schema:
      $ref: "#/definitions/Error"
  NotFound:
    description: "Not found"
    schema:
      $ref: "#/definitions/Error"

paths:
  /books/{id}:
    get:
      operationId: getBook
      parameters:
        - name: id
          in: path
          required: true
          type: integer
      responses:
        200:
          description: OK response
        400:
          $ref: "#/responses/BadRequest"
        404:
          $ref: "#/responses/NotFound"
        500:
          description: "Extended error"
          schema:
            $ref: "#/definitions/ExtendedError"

definitions:
  Error:
    type: object
    properties:
      msg:
        type: string

  ExtendedError:
    type: object
    properties:
      msg:
        type: string
      code:
        type: integer

