swagger: '2.0'
info:
  title: swagger-test
  description: Testing Swagger Codegen
  version: 9.0.0
  x-npm-package: swagger-test
basePath: /v1
schemes:
  - http
produces:
  - application/json
consumes:
  - application/json
responses:
  BadRequest:
    description: "Bad Request"
    schema:
      $ref: "#/definitions/BadRequest"
  InternalError:
    description: "Internal Error"
    schema:
      $ref: "#/definitions/InternalError"
  NotFound:
    description: "Not found"
    schema:
      $ref: "#/definitions/NotFound"

paths:
  /books/{id}:
    get:
      operationId: getBook
      parameters:
        - name: id
          in: path
          required: true
          type: integer
          maximum: 4000
      responses:
        200:
          description: OK response
        400:
          description: "Extended error"
          schema:
            $ref: "#/definitions/ExtendedError"
        404:
          $ref: "#/responses/NotFound"
        500:
          $ref: "#/responses/InternalError"

definitions:

  NotFound:
    type: object
    properties:
      message:
        type: string

  BadRequest:
    type: object
    properties:
      message:
        type: string

  InternalError:
    type: object
    properties:
      message:
        type: string
      code:
        type: integer

  ExtendedError:
    type: object
    properties:
      message:
        type: string
      code:
        type: integer

