swagger: '2.0'
info:
  title: wag-patch
  description: Wag Patch
  version: "1.0.0"
  x-npm-package: wag-patch
schemes:
  - http
produces:
  - application/json

paths:
  /wagpatch:
    patch:
      operationId: wagpatch
      description: Special wag patch type
      parameters:
        - name: specialPatch
          x-wag-patch: true
          in: body
          schema:
            $ref: "#/definitions/Data"
      responses:
        200:
          description: OK response
          schema:
            $ref: "#/definitions/Data"

  /wagpatch2:
    patch:
      operationId: wagpatch2
      description: Wag patch with another argument
      parameters:
        - name: other
          in: query
          type: string
        - name: specialPatch
          x-wag-patch: true
          in: body
          schema:
            $ref: "#/definitions/Data"
      responses:
        200:
          description: OK response
          schema:
            $ref: "#/definitions/Data"


definitions:

  Data:
    type: object
    properties:
      id:
        type: string
      num:
        type: integer
      arrayField:
        type: array
        items:
          type: string
      nested:
        $ref: "#/definitions/NestedData"

  NestedData:
    type: object
    properties:
      id:
        type: string
      name:
        type: string
