// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go

// Package client is a generated GoMock package.
package client

import (
	context "context"
	reflect "reflect"

	models "github.com/Clever/wag/samples/v8/gen-go-blog/models"
	gomock "github.com/golang/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {git s
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// GetSectionsForStudent mocks base method.
func (m *MockClient) GetSectionsForStudent(ctx context.Context, studentID string) ([]models.Section, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSectionsForStudent", ctx, studentID)
	ret0, _ := ret[0].([]models.Section)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSectionsForStudent indicates an expected call of GetSectionsForStudent.
func (mr *MockClientMockRecorder) GetSectionsForStudent(ctx, studentID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSectionsForStudent", reflect.TypeOf((*MockClient)(nil).GetSectionsForStudent), ctx, studentID)
}

// PostGradeFileForStudent mocks base method.
func (m *MockClient) PostGradeFileForStudent(ctx context.Context, i *models.PostGradeFileForStudentInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PostGradeFileForStudent", ctx, i)
	ret0, _ := ret[0].(error)
	return ret0
}

// PostGradeFileForStudent indicates an expected call of PostGradeFileForStudent.
func (mr *MockClientMockRecorder) PostGradeFileForStudent(ctx, i interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostGradeFileForStudent", reflect.TypeOf((*MockClient)(nil).PostGradeFileForStudent), ctx, i)
}

// PostSectionsForStudent mocks base method.
func (m *MockClient) PostSectionsForStudent(ctx context.Context, i *models.PostSectionsForStudentInput) ([]models.Section, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PostSectionsForStudent", ctx, i)
	ret0, _ := ret[0].([]models.Section)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PostSectionsForStudent indicates an expected call of PostSectionsForStudent.
func (mr *MockClientMockRecorder) PostSectionsForStudent(ctx, i interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostSectionsForStudent", reflect.TypeOf((*MockClient)(nil).PostSectionsForStudent), ctx, i)
}
