// Automatically generated by MockGen. DO NOT EDIT!
// Source: interface.go

package client

import (
	context "context"
	models "github.com/Clever/wag/samples/gen-go-nils/models"
	gomock "github.com/golang/mock/gomock"
)

// MockClient is a mock of Client interface
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
}

// MockClientMockRecorder is the mock recorder for MockClient
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (_m *MockClient) EXPECT() *MockClientMockRecorder {
	return _m.recorder
}

// NilCheck mocks base method
func (_m *MockClient) NilCheck(ctx context.Context, i *models.NilCheckInput) error {
	ret := _m.ctrl.Call(_m, "NilCheck", ctx, i)
	ret0, _ := ret[0].(error)
	return ret0
}

// NilCheck indicates an expected call of NilCheck
func (_mr *MockClientMockRecorder) NilCheck(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "NilCheck", arg0, arg1)
}
