// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// TeacherSharingRule teacher sharing rule
// swagger:model TeacherSharingRule
type TeacherSharingRule struct {

	// app
	App string `json:"app,omitempty"`

	// created at
	CreatedAt strfmt.DateTime `json:"created_at,omitempty"`

	// district
	District string `json:"district,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// school
	School string `json:"school,omitempty"`

	// school teacher app
	// Pattern: ^[0-9a-f]{24}_[0-9a-f]{24}_[0-9a-f]{24}$
	SchoolTeacherApp string `json:"school_teacher_app,omitempty"`

	// sections
	Sections []string `json:"sections"`

	// teacher
	Teacher string `json:"teacher,omitempty"`

	// teacher app
	// Pattern: ^[0-9a-f]{24}_[0-9a-f]{24}$
	TeacherApp string `json:"teacher_app,omitempty"`

	// updated at
	UpdatedAt strfmt.DateTime `json:"updated_at,omitempty"`
}

// Validate validates this teacher sharing rule
func (m *TeacherSharingRule) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateSchoolTeacherApp(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateSections(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateTeacherApp(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TeacherSharingRule) validateSchoolTeacherApp(formats strfmt.Registry) error {

	if swag.IsZero(m.SchoolTeacherApp) { // not required
		return nil
	}

	if err := validate.Pattern("school_teacher_app", "body", string(m.SchoolTeacherApp), `^[0-9a-f]{24}_[0-9a-f]{24}_[0-9a-f]{24}$`); err != nil {
		return err
	}

	return nil
}

func (m *TeacherSharingRule) validateSections(formats strfmt.Registry) error {

	if swag.IsZero(m.Sections) { // not required
		return nil
	}

	return nil
}

func (m *TeacherSharingRule) validateTeacherApp(formats strfmt.Registry) error {

	if swag.IsZero(m.TeacherApp) { // not required
		return nil
	}

	if err := validate.Pattern("teacher_app", "body", string(m.TeacherApp), `^[0-9a-f]{24}_[0-9a-f]{24}$`); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *TeacherSharingRule) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TeacherSharingRule) UnmarshalBinary(b []byte) error {
	var res TeacherSharingRule
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
