// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// TeacherSharingRule teacher sharing rule
//
// swagger:model TeacherSharingRule
type TeacherSharingRule struct {

	// app
	App string `json:"app,omitempty"`

	// district
	District string `json:"district,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// school
	School string `json:"school,omitempty"`

	// sections
	Sections []string `json:"sections"`

	// teacher
	Teacher string `json:"teacher,omitempty"`
}

// Validate validates this teacher sharing rule
func (m *TeacherSharingRule) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this teacher sharing rule based on context it is used
func (m *TeacherSharingRule) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TeacherSharingRule) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TeacherSharingRule) UnmarshalBinary(b []byte) error {
	var res TeacherSharingRule
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
