// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ThingWithCompositeAttributes thing with composite attributes
// swagger:model ThingWithCompositeAttributes
type ThingWithCompositeAttributes struct {

	// branch
	Branch string `json:"branch,omitempty"`

	// date
	Date strfmt.DateTime `json:"date,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// version
	Version int64 `json:"version,omitempty"`
}

// Validate validates this thing with composite attributes
func (m *ThingWithCompositeAttributes) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *ThingWithCompositeAttributes) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ThingWithCompositeAttributes) UnmarshalBinary(b []byte) error {
	var res ThingWithCompositeAttributes
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
