// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ThingWithRequiredCompositePropertiesAndKeysOnly thing with required composite properties and keys only
// swagger:model ThingWithRequiredCompositePropertiesAndKeysOnly
type ThingWithRequiredCompositePropertiesAndKeysOnly struct {

	// property one
	// Required: true
	PropertyOne *string `json:"propertyOne"`

	// property three
	// Required: true
	PropertyThree *string `json:"propertyThree"`

	// property two
	// Required: true
	PropertyTwo *string `json:"propertyTwo"`
}

// Validate validates this thing with required composite properties and keys only
func (m *ThingWithRequiredCompositePropertiesAndKeysOnly) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePropertyOne(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePropertyThree(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePropertyTwo(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ThingWithRequiredCompositePropertiesAndKeysOnly) validatePropertyOne(formats strfmt.Registry) error {

	if err := validate.Required("propertyOne", "body", m.PropertyOne); err != nil {
		return err
	}

	return nil
}

func (m *ThingWithRequiredCompositePropertiesAndKeysOnly) validatePropertyThree(formats strfmt.Registry) error {

	if err := validate.Required("propertyThree", "body", m.PropertyThree); err != nil {
		return err
	}

	return nil
}

func (m *ThingWithRequiredCompositePropertiesAndKeysOnly) validatePropertyTwo(formats strfmt.Registry) error {

	if err := validate.Required("propertyTwo", "body", m.PropertyTwo); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ThingWithRequiredCompositePropertiesAndKeysOnly) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ThingWithRequiredCompositePropertiesAndKeysOnly) UnmarshalBinary(b []byte) error {
	var res ThingWithRequiredCompositePropertiesAndKeysOnly
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
