// Automatically generated by MockGen. DO NOT EDIT!
// Source: interface.go

package server

import (
	context "context"
	models "github.com/Clever/wag/samples/gen-no-definitions/models"
	gomock "github.com/golang/mock/gomock"
)

// Mock of Controller interface
type MockController struct {
	ctrl     *gomock.Controller
	recorder *_MockControllerRecorder
}

// Recorder for MockController (not exported)
type _MockControllerRecorder struct {
	mock *MockController
}

func NewMockController(ctrl *gomock.Controller) *MockController {
	mock := &MockController{ctrl: ctrl}
	mock.recorder = &_MockControllerRecorder{mock}
	return mock
}

func (_m *MockController) EXPECT() *_MockControllerRecorder {
	return _m.recorder
}

func (_m *MockController) DeleteBook(ctx context.Context, i *models.DeleteBookInput) error {
	ret := _m.ctrl.Call(_m, "DeleteBook", ctx, i)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockControllerRecorder) DeleteBook(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "DeleteBook", arg0, arg1)
}
