// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// OmitEmpty omit empty
//
// swagger:model OmitEmpty
type OmitEmpty struct {

	// array field not omitted
	ArrayFieldNotOmitted []string `json:"arrayFieldNotOmitted"`

	// array field omitted
	ArrayFieldOmitted []string `json:"arrayFieldOmitted,omitempty"`
}

// Validate validates this omit empty
func (m *OmitEmpty) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *OmitEmpty) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OmitEmpty) UnmarshalBinary(b []byte) error {
	var res OmitEmpty
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
